//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocaLabs.Conversion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocaLabs.Conversion.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert from type {0} to type {1}..
        /// </summary>
        internal static string cannot_convert_from_0_to_1 {
            get {
                return ResourceManager.GetString("cannot_convert_from_0_to_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input argument can be only of string or Guid type..
        /// </summary>
        internal static string input_argument_can_be_only_string_or_guid {
            get {
                return ResourceManager.GetString("input_argument_can_be_only_string_or_guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} cannot be converted to byte array..
        /// </summary>
        internal static string type_0_cannot_be_converted_to_byte_array {
            get {
                return ResourceManager.GetString("type_0_cannot_be_converted_to_byte_array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown underlying enum type {0}..
        /// </summary>
        internal static string unknown_underlying_enum_type_0 {
            get {
                return ResourceManager.GetString("unknown_underlying_enum_type_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} is not defined for enum {1}..
        /// </summary>
        internal static string value_0_is_not_defined_for_enum_1 {
            get {
                return ResourceManager.GetString("value_0_is_not_defined_for_enum_1", resourceCulture);
            }
        }
    }
}
